module.exports={
    plugins:[
        require('autoprefixer')
    ],
    module:{
        rule:[
            {
            test:/\.css$/,
            use:ExtractTextPlugin.extract({
                fallback:'style-loader',
                use:[{
                    loader:"css-loader",
                    options:{importLoaders:1}
                }]
            })
            },'postcss-loader'
        ]
    }
}